### ISSUE TITLE
how to request api/users after authenticate?

### ISSUE THREAD

**Issue by techmango** [thomas-kendall/trivia-microservices#1]
I can generate token when i request localhost:8080/authenticate, but I can't request other api page like 'localhost:8080/api/users' but just return 403 status.

how to request api/users after authenticate?

**Comment by thomas-kendall** [comment]
Once you generate the token, you would use that token on each request after that as a request header in the form of "Authorization: XYZ123ABC" where XYZ123ABC is the token you generated.

**Comment by techmango** [comment]
Thanks!
One more question, do you have a more safer solution to avoid "Replay Attacks"?

**Comment by thomas-kendall** [comment]
Inherently, JWTs have an expiration date so the risk of a replay attack is not high when used with HTTPS.
I do not have a safer solution but it has been done and is in the JWT spec. [This page](https://stormpath.com/blog/jwt-the-right-way) has more information. You will have to modify the code to implement.

**Comment by techmango** [comment]
Good,Really appreciate for your great help!
